
server:
  port: 9703
  
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: bhaumik@23
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 600000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 100000
      leak-detection-threshold: 10000
  application:
    name: murraco-jwt
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.Oracle10gDialect 
  main:
     allow-bean-definition-overriding: true
     
security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds
      
UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data
 
    
    

